# Puerto
server.port=8080

# H2 en memoria (modo MySQL para que no se queje por dialectos)
spring.datasource.url=jdbc:h2:mem:flighton;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false


# Configuraciones del servicio de Machine Learning
ml.ds.base-url=http://127.0.0.1:8000
ml.timeout.ms=8000